[WIP] User not signed in on refresh
agroeasy/agroeasy pull request #2
Opened 2019-03-29 11:37 UTC by Simpcyclassy

2019-04-01 13:59 UTC, Way2nnadi commented on src/components/app/reducers.js
> +            isLoggedIn: !!user === true,
all you need is `!!user`

2019-04-01 13:59 UTC, Way2nnadi commented on src/components/app/reducers.js
> +        Cookies.set( token, user, { expires: EXPIRATION });
remove space before `token`

2019-04-01 14:00 UTC, Way2nnadi commented
@chioma can you upload of video showing you testing this functionality?

2019-04-01 21:54 UTC, Simpcyclassy commented
Sure, only that I have to test it with the token as a unique string cause the token being sent is not constant which is not meant to be so.

2019-04-01 23:20 UTC, Simpcyclassy commented
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34488930/55365620-10ed3f00-54dd-11e9-9c82-001e9e5b7936.gif)

2019-04-02 19:24 UTC, EngrEric commented on src/components/app/actions.js
> +    payload,
you aren't making use of the payload, remove then

2019-04-02 19:36 UTC, EngrEric commented
looks good but your bug is not fixed yet, i ran the branch locally but it seems not fixed.

2019-04-13 15:46 UTC, EngrEric requested changes
Looks good but needs to retain user data on refresh too.
It does not work for now

2019-04-13 15:47 UTC, joshuaobinna reviewed
Looks good but more work is needed

2019-04-13 15:54 UTC, enyeInc commented on package.json
> +>>>>>>> master
you messed up the merge conflicts

2019-04-13 15:56 UTC, enyeInc commented on src/components/app/components/App.js
> +
nit - remove empty line

2019-04-13 15:56 UTC, enyeInc commented on src/components/app/reducers.js
> +        Cookies.set("token", user, { expires: EXPIRATION });
`"token"` should be saved to the constants file

2019-04-13 15:57 UTC, enyeInc commented on src/components/app/reducers.js
> +        Cookies.expire("token");
here as well

2019-04-13 16:01 UTC, Simpcyclassy commented on package.json
> +>>>>>>> master
wow. I did not save correctly

2019-05-15 09:43 UTC, EngrEric commented
i will be closing this PR given that we are adopting a new method for sign in

2019-05-15 09:43 UTC, closed without merging