Feature/mr ceo/cart
agroeasy/agroeasy pull request #26
Opened 2019-07-01 20:16 UTC by MrCEO63

2019-07-03 23:45 UTC, mcbobby7 approved these changes

2019-07-15 12:18 UTC, EngrEric commented on src/components/app/actions.js
> +    payload: cartCount,
```
export const setCartCount = payload=> ({
    payload,
```

2019-07-15 12:20 UTC, EngrEric commented on src/components/app/components/Navbar.js
> +        setInterval(() => {
why are you using `setInterval()` here?

2019-07-15 12:21 UTC, EngrEric commented on src/components/app/components/Navbar.js
> +        console.log(this.props);
remove `console.log`

2019-07-15 12:23 UTC, EngrEric commented on src/components/app/components/styles.css
> +  background-color: transparent !important;
it is not recommended to use `!important` , if there is a better way please remove it

2019-07-15 12:25 UTC, EngrEric commented on src/components/app/selectors.js
> + * {@link module:signin/constants::INITIAL_STATE constants::INITIAL_STATE}).
edit comments to reflect what you are doing

2019-07-15 12:28 UTC, EngrEric commented on src/components/cart/components/Cart.js
> +];
move data to constant

2019-07-15 12:29 UTC, EngrEric commented on src/components/cart/components/Cart.js
> +                                style={{ backgroundColor: '#001529' }}
no inline styling.
move to `styles.css`

2019-07-15 12:32 UTC, EngrEric requested changes
Looks good, just require some changes. and also validate that the feature you added is working as required.

2019-07-15 14:43 UTC, enyeInc commented on src/components/app/components/Navbar.js
> +                    <Item key="cart" className={'bg-transparent'}>
`className='bg-transparent'`

2019-07-15 14:45 UTC, enyeInc commented on src/components/cart/components/Cart.js
> +    }
why are you storing items on the `localStorage` and `sessionStorage`?

2019-07-15 14:45 UTC, enyeInc commented on src/components/cart/components/Cart.js
> +        window.sessionStorage.setItem('cartTotal', total);
again why do this object live on the `localStorage` and `sessionStorage`

2019-07-15 14:46 UTC, enyeInc commented on src/components/cart/components/Cart.js
> +        });
use `Array.reduce` to do the logic from `line 61 - 65`

2019-07-15 14:47 UTC, enyeInc commented
@MrCEO63 and @EngrEric Why are you guys storing app level data outside of the redux store? This is an anti pattern and should be fixed right away

2019-09-10 11:03 UTC, EngrEric commented on db/config.js
> +export const MONGO_DB_URL = 'mongodb://localhost:27017/agroeasydb';
this is local db and may not work for everybody. uncomment the remote part

2019-09-10 11:14 UTC, EngrEric reviewed
I think the backend looks good to me. Can you push your frontend changes and mention me the part you are having issues to get the user data.
Also did you test out this backend with postman to make sure its working as desired

2021-02-05 13:25 UTC, closed without merging